[package]
name = "reach_c_abi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
engine = { path = "../../engine" }
once_cell = "1"
serde_json.workspace = true
